name: OrgBook-App Build
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: "."

env:
  BUILD_CONFIG: orgbook-app
  NAMESPACE: ${{ secrets.OpenShiftNamespace }}

jobs:

  openshift-build:
    runs-on: ubuntu-latest
    # needs: []
    steps:
      - name: Run OpenShift build
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL }}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'start-build ${BUILD_CONFIG} -n ${NAMESPACE} --follow'

      - name: Check OpenShift build status
        run: |
          last_build=$(oc get builds -n ${NAMESPACE} --selector=buildconfig=${BUILD_CONFIG} --sort-by='.metadata.creationTimestamp' -o jsonpath='{.items[-1].metadata.name}')
          echo "Build name: ${last_build}"
          build_status=$(oc get build ${last_build} -o jsonpath='{.status.phase}')
          if [[ "$build_status" != "Complete" ]]; then
            echo "Build failed"
            exit 1
          fi
